# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98acce489688787e15fe2a4a404e2ac5d4c40534e8f5399d52552e0d33b480349855da55f18928bd265a66d4655873930b2b36651e3d77cb3fe78e25166b1095

test:
  secret_key_base: c5e732ed2b7ae9d7b5d4635e6885df5b9356bca5519da1e2e431e198c9459013c3d109bc9e9e1d0868214b2e39126ceb69b5351404b847fe9b4efa9b435b06a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
